routes/admin.php
<?php

Route::group(['prefix'  =>  'admin'], function () {
    
    Route::get('login', 'Admin\LoginController@showLoginForm')->name('admin.login');
    Route::post('login', 'Admin\LoginController@login')->name('admin.login.post');
    Route::get('logout', 'Admin\LoginController@logout')->name('admin.logout');
    Route::get('/forgot-password', function () {
        return view('auth.forgot-password');
    })->middleware(['guest'])->name('password.request');
    // Route::resource('products', 'Admin\ProductController');
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/','Admin\PageController@dashboard')->name('admin.dashboard');

        Route::group(['prefix' => 'profiles'], function () {
            Route::get('/','Admin\ProfileController@index')->name('admin.profiles.index');
            Route::post('/{id}/update', 'Admin\ProfileController@update')->name('admin.profiles.update');
        });

        Route::group(['prefix' => 'accounts'], function () {
            Route::get('/','Admin\AccountSettingController@index')->name('admin.accounts.index');
        });

        Route::get('/settings', 'Admin\SettingController@index')->name('admin.settings');
        Route::post('/settings', 'Admin\SettingController@update')->name('admin.settings.update');

        Route::group(['prefix'  =>   'categories'], function () {
            Route::get('/', 'Admin\CategoryController@index')->name('admin.categories.index');
            Route::get('/lists', 'Admin\CategoryController@lists')->name('admin.categories.lists');
            Route::get('/create', 'Admin\CategoryController@create')->name('admin.categories.create');
            Route::post('/store', 'Admin\CategoryController@store')->name('admin.categories.store');
            Route::get('/{id}/edit', 'Admin\CategoryController@edit')->name('admin.categories.edit');
            Route::post('/update', 'Admin\CategoryController@update')->name('admin.categories.update');
            Route::get('/{id}/delete', 'Admin\CategoryController@destroy')->name('admin.categories.delete');
        });

        Route::group(['prefix' => 'foods'], function () {
            Route::get('/','Admin\FoodsController@index')->name('admin.foods.index');
            Route::post('/import','Admin\FoodsController@import')->name('admin.foods.import');
        });

        Route::group(['prefix' => 'insecticides'], function () {
            Route::get('/','Admin\InsecticidesController@index')->name('admin.insecticides.index');
            Route::post('/import', 'Admin\InsecticidesController@import')->name('admin.insecticides.import');
        });

        Route::group(['prefix' => 'manager_users'], function () {
            Route::get('/','Admin\ManagementUsersController@index')->name('admin.manager_users.index');
            Route::get('/{id}/edit','Admin\ManagementUsersController@edit')->name('admin.manager_users.edit');
            Route::post('/store','Admin\ManagementUsersController@store')->name('admin.manager_users.store');
            Route::post('/{id}/update','Admin\ManagementUsersController@update')->name('admin.manager_users.update');
            Route::get('/{id}/delete','Admin\ManagementUsersController@destroy')->name('admin.manager_users.delete');
            Route::post('/import','Admin\ManagementUsersController@import')->name('admin.manager_users.import');
        });

        Route::group(['prefix' => 'seasonals'], function () {
            Route::get('/', 'Admin\SeasonalController@index')->name('admin.seasonals.index');
            Route::get('/{id}/show', 'Admin\SeasonalController@show')->name('admin.seasonals.show');
            Route::get('/{id}/edit', 'Admin\SeasonalController@edit')->name('admin.seasonals.edit');
            Route::post('/store', 'Admin\SeasonalController@store')->name('admin.seasonals.store');
            Route::post('/{id}/update', 'Admin\SeasonalController@update')->name('admin.seasonals.update');
            Route::get('/{id}/delete', 'Admin\SeasonalController@destroy')->name('admin.seasonals.delete');
        });

        Route::group(['prefix' => 'managerPrice'], function () {
            Route::get('/','Admin\ManagementPriceController@index')->name('admin.managementPrice.index');
        });

        Route::group(['prefix' => 'managerRoles'], function () {
            Route::get('/', 'Admin\ManagementRoleController@index')->name('admin.managementRole.index');
        });

        Route::group(['prefix' => 'managerCropPlantAnimals'], function () {
            Route::get('/','Admin\ManagementCropPlantAnimalController@index')->name('admin.manager_crop_plant_animals.index');
            Route::post('/store', 'Admin\ManagementCropPlantAnimalController@store')->name('admin.manager_crop_plant_animals.store');
            Route::get('/{id}/edit', 'Admin\ManagementCropPlantAnimalController@edit')->name('admin.manager_crop_plant_animals.edit');
            Route::post('/{id}/update', 'Admin\ManagementCropPlantAnimalController@update')->name('admin.manager_crop_plant_animals.update');
            Route::get('/{id}/delete', 'Admin\ManagementCropPlantAnimalController@destroy')->name('admin.manager_crop_plant_animals.delete');
        });

        Route::group(['prefix' => 'posts'], function () {
            Route::get('/','Admin\PostsController@index')->name('admin.posts.index');
            Route::post('/store','Admin\PostsController@store')->name('admin.posts.store');
            Route::get('/{id}/show','Admin\PostsController@show')->name('admin.posts.show');
            Route::get('/map','Admin\PostsController@map')->name('admin.posts.map');
            Route::get('/{id}/edit','Admin\PostsController@edit')->name('admin.posts.edit');
            Route::post('/{id}/update','Admin\PostsController@update')->name('admin.posts.update');
            Route::get('/{id}/delete','Admin\PostsController@destroy')->name('admin.posts.delete');
            Route::get('image/{id}/delete','Admin\PostsController@destroyImage')->name('admin.posts.images.delete');
            Route::get('/{id}/accept', 'Admin\PostsController@accept')->name('admin.posts.accept');
            Route::get('/index/blockUsers', 'Admin\PostsController@indexBlockUsers')->name('admin.posts.indexBlockUsers');
            Route::post('/blockAjax','Admin\PostsController@blockAjax')->name('admin.posts.blockAjax');
            Route::post('/unblockAjax', 'Admin\PostsController@unblockAjax')->name('admin.posts.unblockAjax');
        });

        Route::group(['prefix' => 'groups'], function () {
            Route::get('/','Admin\GroupController@index')->name('admin.groups.index');
            Route::post('/store','Admin\GroupController@store')->name('admin.groups.store');
            Route::get('/{id}/edit','Admin\GroupController@edit')->name('admin.groups.edit');
            Route::get('/{id}/show','Admin\GroupController@show')->name('admin.groups.show');
            Route::post('/{id}/update','Admin\GroupController@update')->name('admin.groups.update');
            Route::get('/{id}/delete','Admin\GroupController@destroy')->name('admin.groups.delete');
            Route::get('/{id}/accept','Admin\GroupController@accept')->name('admin.groups.accept');
            Route::post('/acceptAjax','Admin\GroupController@acceptAjax')->name('admin.groups.acceptAjax');
        });

        Route::group(['prefix' => 'polls'], function () {
            Route::get('/','Admin\PollManagerController@home')->name('admin.polls.home');
            Route::get('/index','Admin\PollManagerController@index')->name('admin.polls.index');
            Route::get('/create','Admin\PollManagerController@create')->name('admin.polls.create');
            Route::post('/store','Admin\PollManagerController@store')->name('admin.polls.store');
            Route::get('/edit/{poll}', 'Admin\PollManagerController@edit')->name('admin.polls.edit');
            Route::patch('/update/{poll}', 'Admin\PollManagerController@update')->name('admin.polls.update');
            Route::get('/admin/polls/{poll}/options/add', ['uses' => 'Admin\OptionManagerController@push', 'as' => 'admin.polls.options.push']);
            Route::post('/admin/polls/{poll}/options/add', ['uses' => 'Admin\OptionManagerController@add', 'as' => 'admin.polls.options.add']);
            Route::get('/admin/polls/{poll}/options/remove', ['uses' => 'Admin\OptionManagerController@delete', 'as' => 'admin.polls.options.remove']);
            Route::delete('/admin/polls/{poll}/options/remove', ['uses' => 'Admin\OptionManagerController@remove', 'as' => 'admin.polls.options.remove']);
            Route::delete('/admin/polls/{poll}', ['uses' => 'Admin\PollManagerController@remove', 'as' => 'admin.polls.remove']);
            Route::patch('/admin/polls/{poll}/lock', ['uses' => 'Admin\PollManagerController@lock', 'as' => 'admin.polls.lock']);
            Route::patch('/admin/polls/{poll}/unlock', ['uses' => 'Admin\PollManagerController@unlock', 'as' => 'admin.polls.unlock']);
        });

        Route::group(['prefix' => 'options'], function () {
            Route::get('/', 'Admin\OptionManagerController@index')->name('admin.options.index');
        });

        Route::group(['prefix' => 'votes'], function () {
            Route::get('/', 'Admin\VoteManagerController@index')->name('admin.votes.index');
        });

        Route::group(['prefix'  =>   'brands'], function () {
            Route::get('/', 'Admin\BrandController@index')->name('admin.brands.index');
            Route::get('/create', 'Admin\BrandController@create')->name('admin.brands.create');
            Route::post('/store', 'Admin\BrandController@store')->name('admin.brands.store');
            Route::get('/{id}/edit', 'Admin\BrandController@edit')->name('admin.brands.edit');
            Route::post('/update', 'Admin\BrandController@update')->name('admin.brands.update');
            Route::get('/{id}/delete', 'Admin\BrandController@delete')->name('admin.brands.delete');
        });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

require 'admin.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/auth/redirect/{provider}','Site\SocialController@redirect');
Route::get('/callback/{provider}','Site\SocialController@callback');

Route::get('/', 'Site\PostsController@index')->name('site.pages.home');
Route::get('/products', 'Site\ProductController@index')->name('site.products.index');
Route::group(['middleware' => ['auth']], function () {
    // Orders
    Route::group(['prefix' => 'orders'], function () {
        Route::get('/{id}','Site\OrderController@index')->name('site.orders.index');
        Route::post('/store','Site\OrderController@store')->name('site.orders.store');
        Route::get('checkout/payment/complete', 'Site\OrderController@complete')->name('checkout.payment.complete');
    });
    // Role and permission
    Route::resource('roles', 'Site\RoleController');
    Route::resource('users', 'Site\UserController');
    Route::resource('admins', 'Site\AdminController');
    Route::post('/checkout', 'Site\CheckoutController@getCheckout')->name('checkout.index');
    Route::post('/checkout/order', 'Site\CheckoutController@placeOrder')->name('checkout.place.order');
    Route::get('/checkout/product/payment/complete', 'Site\CheckoutController@complete')->name('checkout.product.payment.complete');
    Route::get('/checkoutVnPay','Site\CheckoutController@checkoutVnPay')->name('site.checkout.vnpay');
    Route::post('/vnPayPost','Site\CheckoutController@vnPayPost')->name('site.checkout.vnPayPost');
    Route::get('/checkout/return-vnpay','Site\CheckoutController@return')->name('site.checkout.return');
    // PROFILE
    Route::group(['prefix' => 'profile'], function () {
        Route::get('/', 'Site\ProfileController@index')->name('site.profile.index');
        Route::get('/{id}/show', 'Site\ProfileController@show')->name('site.profile.show');
        Route::get('/login', 'Site\LoginController@showLogin')->name('site.login.showLogin');
        Route::post('/storeLogin', 'Site\LoginController@storeLogin')->name('site.login.storeLogin');
        Route::get('/register', 'Site\LoginController@showRegister')->name('site.register.showRegister');
        Route::post('/storeRegister', 'Site\LoginController@storeRegister')->name('site.register.storeRegister');
        Route::get('/logout', 'Site\LoginController@logout')->name('site.logout');
        Route::post('/{id}/upload', 'Site\ProfileController@uploadImage')->name('site.profile.upload.image');
        Route::post('/follow', 'Site\FriendController@follow')->name('site.profile.follow');
        Route::post('/unFollow', 'Site\FriendController@unFollow')->name('site.profile.unFollow');
    });
    // ACCOUNT
    Route::group(['prefix' => 'accounts'], function () {
        Route::get('/', 'Site\AccountController@index')->name('site.accounts.index');
        Route::post('/update/{user_id}', 'Site\AccountController@update')->name('site.accounts.update');
        Route::get('account/orders', 'Site\AccountController@getOrders')->name('site.account.orders');
        Route::get('/{orderNumber}/showOrder','Site\AccountController@showOrder')->name('site.accounts.showOrder');
    });
    // FRIEND
    Route::group(['prefix' => 'friends'], function () {
        Route::get('/', 'Site\FriendController@index')->name('site.friends.index');
        Route::get('/groupFriends', 'Site\FriendController@showGroupFriends')->name('site.friends.group_friends');
        Route::get('/{id}/show','Site\FriendController@show')->name('site.friends.show');
        Route::post('/block','Site\FriendController@block')->name('site.friends.block');
        Route::post('/unBlock', 'Site\FriendController@unBlock')->name('site.friends.unBlock');
    });
    Route::group(['prefix' => 'relationship'], function () {
        Route::post('/ajaxFriend', 'Site\RelationshipController@ajaxFriend')->name('site.relationship.ajaxFriend');
        Route::post('/ajaxSendRequestFriend', 'Site\RelationshipController@ajaxSendRequestFriend')->name('site.relationship.ajaxFriend');
    });

    Route::group(['prefix' => 'experience_farms'], function () {
        Route::get('/', 'Site\ExperienceFarmController@index')->name('site.experience_farms.index');
        Route::get('/crops', 'Site\ExperienceFarmController@cropsIndex')->name('site.experience_farms.crops.index');
        Route::get('/animals', 'Site\ExperienceFarmController@animalsIndex')->name('site.experience_farms.animals.index');
        Route::post('/store', 'Site\ExperienceFarmController@store')->name('site.experience_farms.store');
        Route::get('/{id}/edit', 'Site\ExperienceFarmController@edit')->name('site.experience_farms.edit');
        Route::post('/{id}/update', 'Site\ExperienceFarmController@update')->name('site.experience_farms.update');
        Route::get('/{id}/delete', 'Site\ExperienceFarmController@destroy')->name('site.experience_farms.delete');
        Route::get('/addCalendar', 'Site\ExperienceFarmController@addCalendar')->name('site.experience_farms.add_calendar');
        Route::get('/list', 'Site\ExperienceFarmController@list')->name('site.experience_farms.list');
        Route::post('/list/ajaxToggleLike', 'Site\ExperienceFarmController@ajaxToggleLike')->name('site.experience_farms.ajaxToggleLike');
        // Like
        Route::post('/like', 'Site\ExperienceFarmController@like')->name('site.experience_farms.like');
        // Dislike
        Route::post('/dislike', 'Site\ExperienceFarmController@dislike')->name('site.experience_farms.dislike');
        Route::get('/{id}/modify','Site\ExperienceFarmController@modify')->name('site.experience_farms.modify');
    });
    Route::post('ajaxRequestLike', 'Site\PostsController@ajaxRequestLike')->name('ajaxRequest');
    Route::post('ajaxRequestDisLike', 'Site\PostsController@ajaxRequestDisLike')->name('ajaxRequest');
    Route::group(['prefix' => 'posts'], function () {
        Route::post('/store', 'Site\PostsController@store')->name('site.posts.store');
        Route::get('/{id}/show', 'Site\PostsController@show')->name('site.posts.show');
        Route::get('/{slug}/post', 'Site\PostsController@showSlug')->name('site.posts.show_slug');
        Route::get('/{id}/delete', 'Site\PostsController@destroy')->name('site.posts.delete');
        Route::get('/{id}/edit', 'Site\PostsController@edit')->name('site.posts.edit');
        Route::post('/{id}/update', 'Site\PostsController@update')->name('site.posts.update');
        Route::post('/rating', 'Site\PostsController@rating')->name('site.posts.ratings');
        Route::get('/maps', 'Site\PostsController@maps')->name('site.posts.maps');
        // Like
        Route::post('/like', 'Site\PostsController@like')->name('site.posts.like');
        // Dislike
        Route::post('/dislike', 'Site\PostsController@dislike')->name('site.posts.dislike');
        Route::get('/create-summernote','Site\PostsController@indexSummernote')->name('site.posts.create-summernote');
        Route::post('/storeSummernote','Site\PostsController@storeSummernote')->name('site.posts.storeSummernote');
    });

    Route::group(['prefix' => 'comments'], function () {
        Route::get('/', 'Site\CommentsController@index')->name('site.comments.index');
        Route::post('/store', 'Site\CommentsController@store')->name('site.comments.store');
    });

    Route::get('/ajaxSearch', 'Site\RelationshipController@ajaxSearch')->name('site.search.ajax_search');

    Route::group(['prefix' => 'groups'], function () {
        Route::get('/', 'Site\GroupController@index')->name('site.groups.index');
        Route::post('/store', 'Site\GroupController@store')->name('site.groups.store');
        Route::post('/ajaxSendRequestGroup', 'Site\GroupController@ajaxSendRequestGroup')->name('site.groups.ajax_send_request_group');
        Route::get('/create', 'Site\GroupController@create')->name('site.groups.create');
        Route::get('/{id}/show', 'Site\GroupController@show')->name('site.groups.show');
        Route::get('/chat','Site\GroupController@chat')->name('site.groups.chat');
    });

    Route::get('/userView/{id}', 'Site\FriendController@getuserView')->name('user.view');

    Route::group(['prefix' => 'polls'], function () {
        Route::get('/','Site\PollManagerController@index')->name('site.polls.index');
        Route::get('/create', 'Site\PollManagerController@create')->name('site.polls.create');
        Route::post('/store', 'Site\PollManagerController@store')->name('site.polls.store');
        Route::get('/edit/{poll}', 'Site\PollManagerController@edit')->name('site.polls.edit');
        Route::post('/update/{poll}', 'Site\PollManagerController@update')->name('site.polls.update');
    });

    Route::group(['prefix' => 'products'], function () {
        Route::get('/list', 'Site\ProductController@list')->name('site.products.list');
        Route::get('/{slug}/show', 'Site\ProductController@show')->name('site.products.show');
        Route::post('/product/add/cart', 'Site\ProductController@addToCart')->name('product.add.cart');
        Route::post('/rating', 'Site\ProductController@rating')->name('site.products.rating');
    });

    Route::get('/cart','Site\CartController@getCart')->name('checkout.cart');
    Route::get('/cart/item/{id}/remove', 'Site\CartController@removeItem')->name('checkout.cart.remove');
    Route::get('/cart/clear', 'Site\CartController@clearCart')->name('checkout.cart.clear');
    Route::post('/cart/addCouponRequest', 'Site\CartController@addCoupon');

    Route::group(['prefix' => 'saves'], function () {
        Route::get('/','Site\SaveController@index')->name('site.saves.index');

resources/views/admin/admins/create.blade.php
@extends('site.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Admin</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif



{!! Form::open(array('route' => 'admins.store','method'=>'POST')) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Password:</strong>
            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Confirm Password:</strong>
            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control'))
            !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Role:</strong>
            {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/admin/admins/edit.blade.php
@extends('site.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit New Admin</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


{!! Form::model($admin, ['method' => 'PATCH','route' => ['admins.update', $admin->admin_id]]) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Password:</strong>
            {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Confirm Password:</strong>
            {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' => 'form-control'))
            !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Role:</strong>
            {!! Form::select('roles[]', $roles,$adminRole, array('class' => 'form-control','multiple')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/admin/admins/index.blade.php
@extends('site.app')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Admin Management</h2>
        </div>
        <div class="pull-right">
            <a href="{{route('admins.create')}}" class="btn btn-success">Create New Admin</a>
        </div>
    </div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
    <tr>
        <th>No</th>
        <th>Name</th>
        <th>Email</th>
        <th>Roles</th>
        <th width="280px">Action</th>
    </tr>
    @foreach ($data as $key => $admin)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $admin->name }}</td>
        <td>{{ $admin->email }}</td>
        <td>
            @if(!empty($admin->getRoleNames()))
            @foreach($admin->getRoleNames() as $v)
            <label class="badge badge-success">{{ $v }}</label>
            @endforeach
            @endif
        </td>
        <td>
            <a class="btn btn-info" href="{{ route('admins.show',$admin->admin_id) }}">Show</a>
            <a class="btn btn-primary" href="{{ route('admins.edit',$admin->admin_id) }}">Edit</a>
            {!! Form::open(['method' => 'DELETE','route' => ['admins.destroy', $admin->admin_id],'style'=>'display:inline']) !!}
            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
            {!! Form::close() !!}
        </td>
    </tr>
    @endforeach
</table>

{!! $data->render() !!}
@endsection

resources/views/admin/admins/show.blade.php
@extends('site.app')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Admin</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('admins.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $admin->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $admin->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Roles:</strong>
            @if(!empty($admin->getRoleNames()))
            @foreach($admin->getRoleNames() as $v)
            <label class="badge badge-success">{{ $v }}</label>
            @endforeach
            @endif
        </div>
    </div>
</div>
@endsection